baseURL = 'https://writebyhumans.com'
languageCode = 'en-us'
title = "WriteByHumans"
theme= 'paper'
[params]
twitter = 'test'                # twitter.com/YOUR_TWITTER_ID
github = ''                  # github.com/YOUR_GITHUB_ID
[menu]
[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 10
